[package]
name = "raftpico"
version = "0.1.0"
edition = "2021"

[dependencies]
raftbare = "0.1.1"
rand = "0.8.5"

[dev-dependencies]
clap = { version = "4.5.16", features = ["derive"] }
orfail = "1.1.0"
tiny_http = "0.12.0"

[patch.'crates-io']
raftbare = { path = "../raftbare/" }
